// Code generated by MockGen. DO NOT EDIT.
// Source: parser/parser.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	x "github.com/mihaichiorean/monidog/parser"
)

// MockLog is a mock of Log interface
type MockLog struct {
	ctrl     *gomock.Controller
	recorder *MockLogMockRecorder
}

// MockLogMockRecorder is the mock recorder for MockLog
type MockLogMockRecorder struct {
	mock *MockLog
}

// NewMockLog creates a new mock instance
func NewMockLog(ctrl *gomock.Controller) *MockLog {
	mock := &MockLog{ctrl: ctrl}
	mock.recorder = &MockLogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockLog) EXPECT() *MockLogMockRecorder {
	return m.recorder
}

// MockLogParser is a mock of LogParser interface
type MockLogParser struct {
	ctrl     *gomock.Controller
	recorder *MockLogParserMockRecorder
}

// MockLogParserMockRecorder is the mock recorder for MockLogParser
type MockLogParserMockRecorder struct {
	mock *MockLogParser
}

// NewMockLogParser creates a new mock instance
func NewMockLogParser(ctrl *gomock.Controller) *MockLogParser {
	mock := &MockLogParser{ctrl: ctrl}
	mock.recorder = &MockLogParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockLogParser) EXPECT() *MockLogParserMockRecorder {
	return m.recorder
}

// Parse mocks base method
func (m *MockLogParser) Parse(arg0 string) (x.Log, error) {
	ret := m.ctrl.Call(m, "Parse", arg0)
	ret0, _ := ret[0].(x.Log)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse
func (mr *MockLogParserMockRecorder) Parse(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockLogParser)(nil).Parse), arg0)
}

// LogType mocks base method
func (m *MockLogParser) LogType() string {
	ret := m.ctrl.Call(m, "LogType")
	ret0, _ := ret[0].(string)
	return ret0
}

// LogType indicates an expected call of LogType
func (mr *MockLogParserMockRecorder) LogType() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogType", reflect.TypeOf((*MockLogParser)(nil).LogType))
}
